# Custom metadata preserved from original skill
# This file is used by Context Cascade hooks for extended functionality

category: Database Specialists
complexity: High
triggers:
  - sql
  - postgresql
  - mysql
  - database optimization
  - query optimization
  - indexes
  - explain plan
  - database performance
  - postgres
  - mariadb
_migration:
  source_path: C:\Users\17175\claude-code-plugins\ruv-sparc-three-loop-system\skills\specialists\database-specialists\sql-database-specialist
  category: specialists
  migrated_at: 2025-12-28T15:56:25.127Z
  version: 2.0.0
