# Custom metadata preserved from original skill
# This file is used by Context Cascade hooks for extended functionality

version: 1.0.0
category: utilities
tags:
  - prompt-engineering
  - optimization
  - ai-systems
  - llm
agents:
  - researcher
  - coder
difficulty: intermediate
estimated_duration: 20-40min
success_criteria:
  - Prompt structure optimized
  - Anti-patterns eliminated
  - Evidence-based techniques applied
  - Effectiveness validated
validation_method: A/B testing
dependencies:
  - claude-flow@alpha
prerequisites:
  - Prompt to optimize OR use case defined
outputs:
  - Optimized prompt
  - Analysis report
  - A/B test results
triggers:
  - Poor AI response quality
  - Inconsistent outputs
  - New prompt needed
  - Prompt refactoring required
author: ruv
_migration:
  source_path: C:\Users\17175\claude-code-plugins\ruv-sparc-three-loop-system\skills\tooling\utilities\when-optimizing-prompts-use-prompt-architect
  category: tooling
  migrated_at: 2025-12-28T15:56:25.261Z
  version: 2.0.0
