# Custom metadata preserved from original skill
# This file is used by Context Cascade hooks for extended functionality

version: 1.0.0
category: utilities
tags:
  - intent-analysis
  - cognitive-science
  - disambiguation
  - user-understanding
agents:
  - researcher
  - analyst
  - planner
difficulty: intermediate
estimated_duration: 15-30min
success_criteria:
  - Clear understanding of user intent achieved
  - Ambiguities resolved through targeted questions
  - Actionable task definition created
  - User confirmation obtained
validation_method: user_confirmation
dependencies:
  - claude-flow@alpha
  - hooks-integration
prerequisites:
  - User request captured
  - Context information available
outputs:
  - Interpreted intent document
  - Clarifying questions (if needed)
  - Action plan
triggers:
  - Ambiguous user requests
  - Complex multi-part instructions
  - Vague or unclear requirements
author: ruv
_migration:
  source_path: C:\Users\17175\claude-code-plugins\ruv-sparc-three-loop-system\skills\tooling\utilities\when-analyzing-user-intent-use-intent-analyzer
  category: tooling
  migrated_at: 2025-12-28T15:56:25.249Z
  version: 2.0.0
