# Custom metadata preserved from original skill
# This file is used by Context Cascade hooks for extended functionality

category: Specialized Development
complexity: Medium-High
triggers:
  - language specialist
  - python typescript
  - multi-language
  - backend development
  - type safety
  - api development
version: 1.0.0
tags:
  - specialists
  - domain-expert
author: ruv
_migration:
  source_path: C:\Users\17175\claude-code-plugins\ruv-sparc-three-loop-system\skills\specialists\language-specialists
  category: specialists
  migrated_at: 2025-12-28T15:56:25.148Z
  version: 2.0.0
