# Custom metadata preserved from original skill
# This file is used by Context Cascade hooks for extended functionality

category: specialists
version: 1.0.0
triggers:
  - art prompt
  - image generation
  - visual composition
  - aesthetic framework
  - generate art
  - combine art styles
mcp_servers: required: [] optional: [memory-mcp]
_migration:
  source_path: C:\Users\17175\claude-code-plugins\ruv-sparc-three-loop-system\skills\specialists\visual-art-composition
  category: specialists
  migrated_at: 2025-12-28T15:56:25.199Z
  version: 2.0.0
