# Custom metadata preserved from original skill
# This file is used by Context Cascade hooks for extended functionality

category: Frontend Development
complexity: High
tier: Gold
triggers:
  - frontend
  - react
  - vue
  - ui components
  - css
  - accessibility
  - performance optimization
  - component library
version: 1.0.0
tags:
  - specialists
  - domain-expert
author: ruv
_migration:
  source_path: C:\Users\17175\claude-code-plugins\ruv-sparc-three-loop-system\skills\specialists\frontend-specialists
  category: specialists
  migrated_at: 2025-12-28T15:56:25.138Z
  version: 2.0.0
